package keywords

var (
	// KeywordWeightsCryptocurrency 0  10
	KeywordWeightsCryptocurrency = map[string]int{
		"Cryptocurrency":           5,
		"Bitcoin":                  8,
		"Blockchain":               7,
		"Decentralization":         4,
		"Digital Currency":         6,
		"Currency":                 2,
		"Investment":               9,
		"Financial Revolution":     8,
		"Financial Inclusion":      7,
		"Fintech":                  6,
		"Innovation":               7,
		"Secure Transactions":      8,
		"Transparency":             5,
		"Peer to Peer":             6,
		"Digital Assets":           7,
		"Crypto Market":            8,
		"Growth Potential":         9,
		"Disruptive Technology":    7,
		"Future of Finance":        9,
		"Investment Opportunities": 9,
		"Cryptocurrency Adoption":  7,
	}

	NegativeKeywordsCryptocurrency = map[string]int{
		"Scam":              9,
		"Fraud":             8,
		"Hacking":           7,
		"Loss":              8,
		"Collapse":          9,
		"Regulation":        6,
		"Risk":              7,
		"Volatility":        7,
		"Bubble":            8,
		"Theft":             8,
		"Security Concerns": 7,
		"Ponzi Scheme":      9,
		"Selloff":           8,
		"Downfall":          9,
		"Manipulation":      7,
		"Crash":             9,
		"Bear Market":       8,
		"Hackers":           7,
		"Lawsuit":           6,
		"Market Correction": 7,
	}

	PositiveEconomyKeywords = map[string]int{
		"Growth":              8,
		"Recovery":            7,
		"Expansion":           8,
		"Job Growth":          9,
		"Stability":           7,
		"Investment":          8,
		"Prosperity":          9,
		"Consumer Confidence": 8,
		"Stock Market Rally":  8,
		"Low Unemployment":    9,
		"Business Confidence": 8,
		"Income Increase":     7,
		"Economic Recovery":   8,
		"Increased GDP":       9,
		"Market Boom":         8,
		"Wage Growth":         7,
		"Low Inflation":       9,
		"Inflation":           2,
		"Fiscal Stimulus":     8,
		"Trade Growth":        8,
	}

	NegativeEconomyKeywords = map[string]int{
		"Recession":            8,
		"Economic Downturn":    9,
		"Unemployment":         7,
		"Inflation":            8,
		"Financial Crisis":     9,
		"Market Crash":         9,
		"Decline":              7,
		"Job Loss":             8,
		"Depression":           9,
		"Budget Deficit":       7,
		"Bankruptcy":           8,
		"Poverty":              9,
		"Debt Crisis":          9,
		"Deflation":            8,
		"Stagnation":           7,
		"Trade Deficit":        8,
		"Falling GDP":          9,
		"Foreclosure":          8,
		"Economic Contraction": 9,
		"Crisis":               2,
	}
)
